CREATE TABLE albums (
   album_id INTEGER AUTO_INCREMENT PRIMARY KEY,
   title VARCHAR(255) NOT NULL,
   artist VARCHAR(255) ,
   release_date VARCHAR(255),
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE yoyakus (
   yoyaku_id INTEGER AUTO_INCREMENT PRIMARY KEY,
   name1 VARCHAR(255) NOT NULL,
   zyusyo VARCHAR(255) ,
   kakaku VARCHAR(255) ,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);